[workspace]
members = [
  "rio",
  "rtrees",
]
[package]
name = "rair"
version = "0.1.0"
authors = ["oddcoder <ahmedsoliman@oddcoder.com>"]

[[bin]]
name = "rair"
path = "src/rair.rs"

[dependencies]
